---
abstract: 'Attribute interface for adding tags to methods.'
author:
  - 'Mark Morgan <makk384@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attribute-Method-Tags
provides:
  Attribute::Method::Tags:
    file: lib/Attribute/Method/Tags.pm
    version: 0.10
  Attribute::Method::Tags::Registry:
    file: lib/Attribute/Method/Tags/Registry.pm
    version: 0.10
requires:
  Attribute::Handlers: 0.77
  Test::More: 0.78
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
